### LSTM 

In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM
import numpy as np


ImportError: No module named keras.models

In [ ]:
#the data is saved as a dataframe with two column names: label and review
df = pd.read_csv("C:\\Users\\Myles\\Documents\\Napier Data Science\\Dissertation\\Test data set\\factorsandreturns.csv").fillna(0)

In [ ]:
df[df['return'] == 0].shape

In [ ]:
df = df.sort_values('calendardate')

In [ ]:
df.head()

In [ ]:
df.iloc[:,2:].head()

In [ ]:
train,valid = df[0:6710,:], df[6710:,:]

In [83]:
df = df.set_index('ticker')

In [87]:
df.drop('calendardate',axis=1,inplace=True)

In [88]:
df.head()

accoci        assets  assetsavg       assetsc      assetsnc  \
ticker                                                                   
A      -408000000  8.541000e+09          0  3.848000e+09  4.693000e+09   
ONDK      -503000  1.139933e+09          0  0.000000e+00  0.000000e+00   
ONDS            0  1.206063e+06          0  1.002910e+06  2.031530e+05   
ONTX        -7000  2.313600e+07          0  2.310400e+07  3.200000e+04   
ONVO            0  4.262500e+07          0  4.011700e+07  2.508000e+06   

        assetturnover    bvps     capex       cashneq        cor  ...  \
ticker                                                            ...   
A                   0  14.362 -35000000  2.247000e+09  585000000  ...   
ONDK                0   3.814  -1211000  1.202230e+08   50767000  ...   
ONDS                0  -0.412   -134833  5.162510e+05       6427  ...   
ONTX                0   1.914         0  2.238400e+07          0  ...   
ONVO                0   0.341    -11000  3.748200e+07     125000  ...   

             sgna  sharefactor  sharesbas  shareswadil  taxassets    taxexp  \
ticker                                                                        
A       356000000          1.0  318533054    322000000          0  49000000   
ONDK     23952000          1.0   75046285     79372491          0         0   
ONDS      1214169          1.0   50463732     24033664          0         0   
ONTX      1729000          1.0    5674220      5674125          0         0   
ONVO      3640000          1.0  115890335    113993237          0         0   

        taxliabilities   tbvps  workingcapital    return  
ticker                                                    
A                    0  15.965    2.677000e+09  0.044418  
ONDK                 0  15.257    0.000000e+00 -0.079075  
ONDS                 0   0.049   -9.798867e+06  0.000000  
ONTX                 0   4.077    1.489700e+07  0.137984  
ONVO                 0   0.374    3.682600e+07 -0.108527  

[5 rows x 82 columns]

In [89]:
train,valid = df[0:6710,:], df[6710:,:]

TypeError: '(slice(0, 6710, None), slice(None, None, None))' is an invalid key

In [75]:
#converting dataset into x_train and y_train
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(df.iloc[:,2:])

AttributeError: 'numpy.ndarray' object has no attribute 'iloc'

numpy.ndarray

In [62]:

train,valid = X[0:6710,:], X[6710:,:]

In [63]:
x_train, y_train = [], []
for i in train:
    x_train.append(X[:,:-1])
    y_train.append(X[:,-1:])


In [64]:
x_train, y_train = np.array(x_train), np.array(y_train)

MemoryError: 

In [41]:
X = scaled_data
train,test = X[0:6710], X[6710:]

In [ ]:
x_train = np.reshape(x_train, (x_train.shape[0],x_train.shape[1],1))

In [28]:
X, y = train[:, 0:-1], train[:, -1]
X = X.reshape(X.shape[0], 1, X.shape[1])

In [31]:
X

array([[[7.71669593e-01, 2.49859580e-03, 0.00000000e+00, ...,
         4.01422003e-06, 3.15987378e-03, 2.50516316e-01]],

       [[7.79893383e-01, 3.33477556e-04, 0.00000000e+00, ...,
         4.01422003e-06, 3.01974283e-03, 2.31451808e-01]],

       [[7.79903534e-01, 3.52823317e-07, 0.00000000e+00, ...,
         4.01422003e-06, 9.69832854e-06, 2.31382025e-01]],

       ...,

       [[7.79882606e-01, 5.48124517e-04, 0.00000000e+00, ...,
         4.01422003e-06, 4.77779249e-02, 2.31451808e-01]],

       [[7.78512220e-01, 5.45992183e-04, 0.00000000e+00, ...,
         4.01422003e-06, 4.73238848e-04, 2.31224679e-01]],

       [[7.76305221e-01, 1.41991973e-02, 0.00000000e+00, ...,
         4.01422003e-06, 9.16185263e-02, 2.31451808e-01]]])

In [ ]:
keras.layers.LSTM(units, activation='tanh', recurrent_activation='hard_sigmoid', use_bias=True, kernel_initializer='glorot_uniform', recurrent_initializer='orthogonal', bias_initializer='zeros', unit_forget_bias=True, kernel_regularizer=None, recurrent_regularizer=None, bias_regularizer=None, activity_regularizer=None, kernel_constraint=None, recurrent_constraint=None, bias_constraint=None, dropout=0.0, recurrent_dropout=0.0, implementation=1, return_sequences=False, return_state=False, go_backwards=False, stateful=False, unroll=False)

In [60]:
df.head()

calendardate     accoci        assets  assetsavg       assetsc  \
ticker                                                                  
A        30/09/2018 -408000000  8.541000e+09          0  3.848000e+09   
ONDK     30/09/2018    -503000  1.139933e+09          0  0.000000e+00   
ONDS     30/09/2018          0  1.206063e+06          0  1.002910e+06   
ONTX     30/09/2018      -7000  2.313600e+07          0  2.310400e+07   
ONVO     30/09/2018          0  4.262500e+07          0  4.011700e+07   

            assetsnc  assetturnover    bvps     capex       cashneq  ...  \
ticker                                                               ...   
A       4.693000e+09              0  14.362 -35000000  2.247000e+09  ...   
ONDK    0.000000e+00              0   3.814  -1211000  1.202230e+08  ...   
ONDS    2.031530e+05              0  -0.412   -134833  5.162510e+05  ...   
ONTX    3.200000e+04              0   1.914         0  2.238400e+07  ...   
ONVO    2.508000e+06              0   0.341    -11000  3.748200e+07  ...   

             sgna  sharefactor  sharesbas  shareswadil  taxassets    taxexp  \
ticker                                                                        
A       356000000          1.0  318533054    322000000          0  49000000   
ONDK     23952000          1.0   75046285     79372491          0         0   
ONDS      1214169          1.0   50463732     24033664          0         0   
ONTX      1729000          1.0    5674220      5674125          0         0   
ONVO      3640000          1.0  115890335    113993237          0         0   

        taxliabilities   tbvps  workingcapital    return  
ticker                                                    
A                    0  15.965    2.677000e+09  0.044418  
ONDK                 0  15.257    0.000000e+00 -0.079075  
ONDS                 0   0.049   -9.798867e+06  0.000000  
ONTX                 0   4.077    1.489700e+07  0.137984  
ONVO                 0   0.374    3.682600e+07 -0.108527  

[5 rows x 83 columns]

In [61]:
df.drop('calendardate', axis=1, inplace=True)


In [62]:
target = df['return'].values
target

array([ 0.04441812, -0.07907543,  0.        , ..., -0.05237569,
       -0.12205742, -0.0516129 ])

In [63]:
predictors = df.drop('return', axis=1).values

In [64]:
predictors

array([[-4.0800000e+08,  8.5410000e+09,  0.0000000e+00, ...,
         0.0000000e+00,  1.5965000e+01,  2.6770000e+09],
       [-5.0300000e+05,  1.1399330e+09,  0.0000000e+00, ...,
         0.0000000e+00,  1.5257000e+01,  0.0000000e+00],
       [ 0.0000000e+00,  1.2060630e+06,  0.0000000e+00, ...,
         0.0000000e+00,  4.9000000e-02, -9.7988670e+06],
       ...,
       [-1.8301900e+08,  1.1823650e+09,  0.0000000e+00, ...,
         4.2249000e+07,  1.7257000e+01,  3.2402200e+08],
       [-2.3518700e+08,  3.5408629e+10,  0.0000000e+00, ...,
         0.0000000e+00,  2.9842070e+03,  0.0000000e+00],
       [ 0.0000000e+00,  1.6184000e+07,  0.0000000e+00, ...,
         6.8800000e+05,  5.0100000e-01,  7.9710000e+06]])

In [65]:
target

array([ 0.04441812, -0.07907543,  0.        , ..., -0.05237569,
       -0.12205742, -0.0516129 ])

In [66]:
n_cols = predictors.shape[1]

In [69]:
predictors.shape[1]

81

In [67]:
model = Sequential()

In [68]:
model.add(LSTM(units=50, return_sequences=True, input_shape=(n_cols,)))
model.add(LSTM(units=50))
model.add(Dense(1))

ValueError: Input 0 is incompatible with layer lstm_1: expected ndim=3, found ndim=2

In [ ]:
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(x_train, y_train, epochs=1, batch_size=1, verbose=2)

In [12]:
df.shape

(8387, 82)

In [13]:
#80% training 20% validation split :6710 

train = df.iloc[0:6710,:]
valid = df.iloc[6710:,:]

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:

#converting dataset into x_train and y_train
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(df)

C:\Program Files\Anaconda3\envs\keras\lib\site-packages\sklearn\preprocessing\data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [18]:
import numpy as np

In [19]:
x_train, y_train = [], []
for i in range(len(train)):
    x_train.append(scaled_data[i,0])
    y_train.append(scaled_data[i,0])
x_train, y_train = np.array(x_train), np.array(y_train)

In [21]:
x_train

array([0.77166959, 0.77989338, 0.77990353, ..., 0.77988261, 0.77851222,
       0.77630522])

In [22]:
x_train = np.reshape(x_train, (x_train.shape[0],x_train.shape[1],1))

IndexError: tuple index out of range

In [ ]:
from sklearn.model_selection import train_test_split

reviews_train, reviews_test, y_train, y_test = train_test_split(reviews, labels, test_size=0.20)

# Convolutional Neural Nets

The Keras library allows us to quickly define a CNN architecture, train and evaluate a CNN model with minimal effort. But firstly, we will need to introduce a new concept: __Embeddings__

1. Word Embedding 

Word embeddings are approaches for representing words and documents using vectors. Word embeddings offer an improvement over the traditional bag-of-word encoding paradigms where large sparse vectors are used to represent each word or texts. This way of representing words and texts introduce the sparsity problem, because the number of unique words in a document can be vast and a given word or text is represented by a large vector comprised mostly of zero values. 

Instead, in an embedding, words are represented by __dense vectors__ (smaller vectors with minimal zero values) where a vector represents the projection of the word into a continuous vector space.

The position of a word within the vector space is learnt from text and is based on the surrounding words of a word when it is used. The __position of a word__ in the learnt vector space is known as its __embedding__.

There are a few popular ways of learning word embeddings from text such as Word2Vec, Doc2Vec, Glove and ELMO. 

In addition to these popular methods, word embeddings can be learned as part of a deep learning model as we will see below. 

2. Keras Embedding Layer

Keras offers an Embedding layer that can be used for training neural networks using text data. Keras' Embedding layer takes as input integer encoded data, so that each word is represented by a unique integer. We can use tokenisation to pre-process the data. 

Then, the weights of the Embedding layer are randomly initialized and it is trained to learn an embedding for all of the words in the training dataset.

The Embedding layer is defined as the first hidden layer of a network. It must specify 3 arguments:

1. __input_dim__: the size of the vocabulary in the text data. For example, if your data is integer encoded to values between 0-199, then the input_dim will be 200.
2. __output_dim__: the size of the vector space in which words will be embedded. It is a user-specified value, so test different values for your task.
3. __input_length__: This is the length of input sequences, as you would define for any input layer of a Keras model. For example, if all of your input documents are comprised of 1000 words, this would be 1000.

For example, below we define an Embedding layer with a vocabulary of 1922 (e.g. integer encoded words from 0 to 1921, inclusive), a vector space of 50 dimensions in which words will be embedded, and input documents that have 50 words each.

__Embedding(1922, 50, input_length=30)__

In [ ]:
from keras.preprocessing.text import Tokenizer

In [ ]:
#define the tokenizer: https://keras.io/preprocessing/text/ 
tokenizer = Tokenizer(num_words=2000)

#Use tokenisation only on the training data!
tokenizer.fit_on_texts(reviews_train)

X_train = tokenizer.texts_to_sequences(reviews_train)
X_test = tokenizer.texts_to_sequences(reviews_test)

vocab_size = len(tokenizer.word_index) + 1  # Adding 1 because of reserved 0 index

print(reviews_train[0])
print(X_train[0])
vocab_size

The above method will result in text sequences of variable length of words. To counter this, we can use pad_sequence() which pads the sequence of words with zeros. Additionally you would want to add a maxlen parameter to specify how long the sequences should be. For more oprions of the __pad_sequence__ function look here:  https://keras.io/preprocessing/sequence/ 

In the following code, you can see how to pad sequences with Keras:

In [ ]:
from keras.preprocessing.sequence import pad_sequences

maxlen = 50

X_train = pad_sequences(X_train, padding='post', maxlen=maxlen)
X_test = pad_sequences(X_test, padding='post', maxlen=maxlen)

As we saw during the workbook/lecture, CNNs is just a sequence of different types of layers. Keras allows us to "build" this sequence of layers easily. First, we need to define the type of model, in this case Sequential as follows:

__model = Sequential()__

Then we can add layers as we want, e.g. we can add Convolutional Layers (e.g. Conv1D), Pooling layers (e.g. MaxPooling1D), Fully Connected layers (e.g. Dense) and so on. For a full list of acceptable layers, please see the Keras documentation: https://keras.io/layers/about-keras-layers/ 

Then you simply add the layers of your choice as follows:

__model.add(layers.Dense(1, activation='sigmoid'))__

As you see from the example, you can choose the activation function you want as well. 


In [ ]:
from keras.models import Sequential
from keras import layers

embedding_dim = 50

model = Sequential()
model.add(layers.Embedding(vocab_size, embedding_dim, input_length=maxlen)) #https://keras.io/layers/embeddings/ 
model.add(layers.Conv1D(128, 5, activation='relu')) #https://keras.io/layers/convolutional/
model.add(layers.GlobalMaxPooling1D())
model.add(layers.Dense(10, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.summary()

#spend some time familiarising with the keras documentation. 
#It is imporssible to remember all the options available but you should be able to remember the basics. 

You can now see that we have 129,529 new parameters to train. The 93,950 parameters are derived from vocab_size times the embedding_dim (1879 x 50). These weights of the embedding layer are initialized with random weights and are then adjusted through backpropagation during training. This model takes the words as they come in the order of the sentences as input vectors. You can train it with the following:

In [ ]:
training = model.fit(X_train, y_train, epochs=10, verbose=False, validation_data=(X_test, y_test), batch_size=10)
#details about the model: https://keras.io/models/model/ 

You can see the accuracy during training and testing as follows: 

In [ ]:
loss, accuracy = model.evaluate(X_train, y_train, verbose=False)
print("Training Accuracy: {:.4f}".format(accuracy))
loss, accuracy = model.evaluate(X_test, y_test, verbose=False)
print("Testing Accuracy:  {:.4f}".format(accuracy))

Finally, we can observe how fast the model learns by plotting the historical data of accuracy and loss. We can see that our model would reach a good level of accuracy after only three epochs. 

In [ ]:
import matplotlib.pyplot as plt
plt.style.use('ggplot')

def plot_history(training):
    acc = training.history['acc']
    val_acc = training.history['val_acc']
    loss = training.history['loss']
    val_loss = training.history['val_loss']
    x = range(1, len(acc) + 1)

    plt.figure(figsize=(14, 8))
    plt.subplot(1, 2, 2)
    plt.plot(x, acc, 'b', label='Training acc')
    plt.plot(x, val_acc, 'r', label='Validation acc')
    plt.title('Training and validation accuracy')
    plt.legend()
    plt.subplot(1, 2, 2)
    plt.plot(x, loss, 'b', label='Training loss')
    plt.plot(x, val_loss, 'r', label='Validation loss')
    plt.title('Training and validation loss')
    plt.legend()

In [ ]:
plot_history(training)

### This is a walk through on how to create a train a CNN. As an exercise, familiarise yourself with the Keras exercise and try to add new layers to the CNN architcture / change the values of variables and observe what is happening. You can also try a CNN with the assignment data. 
